pipeline:
  build:
    image: spritsail/docker-build
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    repo: plex-dev
    make: true

  test-bin:
    image: spritsail/docker-test
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    repo: plex-dev
    run: |
      curl --version &&
      xmlstarlet --version

  test:
    image: spritsail/docker-test
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    repo: plex-dev
    curl: ':32400/identity'
    delay: 5
    retry: 10
    pipe: |
      xmlstarlet sel -t -v "/MediaContainer/@version" |
      grep -qw "$(label io.spritsail.version.plex | cut -d- -f1)"

  publish:
    image: spritsail/docker-publish
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    secrets: [ docker_username, docker_password, microbadger_token ]
    when: { branch: [ master ], event: [ push, tag, deployment ] }
    from: plex-dev
    repo: spritsail/plex-media-server
    tags:
      - 'latest'
      - '%label io.spritsail.version.plex | %remsuf [0-9a-f]+$ | %auto 2'

  notify:
    image: spritsail/notify
    when: { status: [ success, failure ] }
    secrets: [ webhook_url, notify_token ]
